### PR TITLE
Find-replace repositery->repository

### PR DESCRIPTION
**Pull request by joeheyming**
Fixed mis-spelled repositery

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
oooops, :D
Could you add a line to the changelog and minor bump the version? :)
Then I'll merge his with pleasure!

**Comment by joeheyming** [comment]
Where is the changelog?

**Comment by AdrieanKhisbe** [comment]
Ooops. Was sure I had one haha, rusty memory.
Well then just update the version in the `.el`, the changelog would wait I make the proper file.

**Comment by joeheyming** [comment]
done

**Comment by AdrieanKhisbe** [comment]
voila :)
Thanks @joeheyming

**Pull request merged**
