### PR TITLE
Use EVM Travis

### PR DESCRIPTION
**Pull request by rejeep**

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
:)

**Comment by AdrieanKhisbe** [comment]
Shall we host the script in the repo or on a github release archive?

(raw....cask-package-toolset.el/scripts/setup-evm.sh )

**Comment by rejeep** [comment]
Ahh, the plan was to update this too? https://github.com/AdrieanKhisbe/cask-package-toolset.el/blob/master/templates/.travis.yml

**Comment by AdrieanKhisbe** [comment]
Haha, I forgot. this one.

---

In fact is to how https://gist.github.com/rejeep/ebcd57c3af83b049833b script, under this repo

``` bash
export PATH="/home/travis/.evm/bin:$PATH"
export PATH="/home/travis/.cask/bin:$PATH"

git clone https://github.com/rejeep/evm.git /home/travis/.evm
evm config path /tmp
evm install emacs-24.3-travis --use --skip

curl -fsSkL https://raw.github.com/cask/cask/master/go | python
```

The problem is whe it has to be updated, or url updated, 
I have to update all the libraries that has used the template.

By hosting it on the repositery, under a logical url, script to use will be always available there.
you see what I mean? :smiley:

**Comment by rejeep** [comment]
> you see what I mean?

No, not really! :smile:

The reason I created a new url was so that I would not break already existing implementations. I think repos should update manually and this repo should generate the new one.

**Comment by AdrieanKhisbe** [comment]
Yep Yep we agree. The point is not to use the older url.

The idea was to not longer update it from now on. But indeed, maybe not the good idea.

(maybe a good alternative would be for the script to be adapt to easily update the `.travis.yml`)

**Pull request merged**
